name: proj
channels:
  - conda-forge
dependencies:
  - descartes
  - doxygen < 1.9
  - geojson
  - matplotlib
  - shapely < 1.8
  - pip
  - pip:
    - breathe
    - pybtex
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
